### PR TITLE
Zigzag encoding fix for signed integer

### PR DESCRIPTION
**Pull request by rstanevich**
This PR applies the changes according to this topic https://developers.google.com/protocol-buffers/docs/encoding#signed-ints
```
Signed Original	Encoded As
0	            0
-1	            1
1	            2
-2	            3
2147483647	    4294967294
-2147483648	    4294967295
```

### CODE REVIEW

**Comment by rstanevich** [comment]
fyi @Rantanen

**Comment by Rantanen** [comment]
Thanks! Sorry for slow reaction. Broke my arm a while ago, but fortunately this PR looks good enough to merg as is!

**Comment by Rantanen** [comment]
Aw. Unfortunately rust fmt checks are failing. Can you run `cargo fmt`, commit changes and push that? (Might need rustfmt component to be installed).

**Comment by Rantanen** [comment]
For some reason that `fmt` pass did not follow the rustfmt.toml in the crate root.

**Comment by Rantanen** [comment]
Still doesn't look right. A simple cargo fmt should do it, if executed in the crate root:

```
~/protofish$ cargo fmt
```

Not sure what is causing the issue on your end. I'll do it myself (mostly to avoid typing more with one hand). :)

**Comment by Rantanen** [comment]
(Not sure when the line endings had changed, that didn't help things - your fmt pass definitely made those better though!)

**Comment by rstanevich** [comment]
thank you Mikko for amazing library and review!

sorry, looks like I have too old rust tools on my personal laptop:
```
Warning: can't set `brace_style = AlwaysNextLine`, unstable features are only available in nightly channel.
```

**Comment by Rantanen** [comment]
Oh, could be I'm also relying on nightly fmt myself so I'll take part of the blame there! Unfortunately I don't want to drop that rule until fmt stops dropping empty lines at start of functions.

In any case it's merged now! Thanks for the contribution!

**Comment by Rantanen** [comment]
Published 0.5.2 on crates.io.

**Pull request merged**
